spring:
  application:
    name: vacation
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url:
    username:
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: HWANCHANG_DB
server:
  port: 8080
jwt:
  token:
    header: x-access-token
    issuer: vacation
    secret:
    expirationTime: 0
