spring:
  config:
    activate:
      on-profile: prod
logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
  file:
    name: /log/debug.log
  exception-conversion-word: "%wEx"
  logback:
    rollingpolicy:
      file-name-pattern: "%d{yyyy-MM}/debug.%d{yyyy-MM-dd}.%i.log.gz"
      max-file-size: 10MB
      max-history: 5
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss.SSS"
    level: "%5p"

---

spring:
  config:
    activate:
      on-profile: dev
logging:
  level:
    root: debug
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
  file:
    name: /log/debug.log
  exception-conversion-word: "%wEx"
  logback:
    rollingpolicy:
      file-name-pattern: "%d{yyyy-MM}/debug.%d{yyyy-MM-dd}.%i.log.gz"
      max-file-size: 10MB
      max-history: 1
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss.SSS"
    level: "%5p"

---

spring:
  config:
    activate:
      on-profile: local
logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.type.descriptor.sql.BasicExtractor: trace
  file:
    name: /log/debug.log
  exception-conversion-word: "%wEx"
  logback:
    rollingpolicy:
      file-name-pattern: "%d{yyyy-MM}/debug.%d{yyyy-MM-dd}.%i.log.gz"
      max-file-size: 10MB
      max-history: 1
  pattern:
    dateformat: "yyyy-MM-dd HH:mm:ss.SSS"
    level: "%5p"
